jo_beet_job:
    resource: "@JoBeetBundle/Controller/"
    type:     annotation

jo_beet:
    resource: "@JoBeetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
