# src/JoBeetBundle/Resources/config/validation.yml

JoBeetBundle\Entity\Job:
  properties:
    type:
      - Choice: { callback: getTypeValues }
      - NotBlank: ~
    email:
     - NotBlank: ~
     - Email: ~