# src/JoBeetBundle/Resources/config/validation.yml

JoBeetBundle\Entity\Job:
  properties:
    type:
      - Choice: { callback: getTypeValues }
      - NotBlank: ~
    company:
      - NotBlank: ~
    position:
      - NotBlank: ~
    location:
      - NotBlank: ~
    description:
      - NotBlank: ~
    how_to_apply:
      - NotBlank: ~
    token:
      - NotBlank: ~
    email:
     - NotBlank: ~
     - Email: ~